### ISSUE TITLE
Set gameplay-changing defaults in hyperspace.xml from true to false, OR be transparent about these defaults and how to edit them

### ISSUE THREAD

**Issue by CommunistMountain** [FTL-Hyperspace/FTL-Hyperspace#352] opened 2024-09-18 02:00 UTC
There are 5 settings in hyperspace.xml which directly affect gameplay, and have their default set to true (as of HS 1.14): preIgniteChargers, repairDroneRecoveryFix, hackingDroneFix, crystalShardFix, defenseDroneFix. Perhaps you could say that the 1st is a convenience setting (you can do it in vanilla as well by fully charging the charger weapon, then unpower it while paused, then jump), and the 4th and 5th are bugfixes, but the 2nd and 3rd definitely affect gameplay.

These are not documented anywhere in README.md or metadata.xml, and users would not realise that these changes are happening (until it becomes obvious for the first 3). They would think that HS is just a dependency for other mods or a UI-improving mod, and be taken by surprise when it also changes gameplay. Basically, **it lacks transparency**. Even a HS dev, Pepson, didn't know that they are in effect by default.

The argument against changing the defaults is backwards compatibility for the sake of other mods. repairDroneRecoveryFix was just implemented so backwards compatibility is not an issue. For the rest, OK, but at the very least it should be made clear to the user in README.md and metadata.xml that:
1. HS makes these gameplay-related changes by default: (list the 4 settings)
2. The user can go to data/hyperspace.xml to find and disable these changes if they wish
3. It is encouraged to explore and edit other settings in hyperspace.xml to their liking

The last point is also important because I've seen people criticise HS because of the dismiss crew sound effect "easter egg". At the time there was no setting for disabling it, and I'm glad that the setting exists in hyperspace.xml now, but users still wouldn't know where to go to edit such settings, or if they can even be edited.

**Comment by ChronoVortex** [comment] 2024-09-30 00:08
Duplicate of #354

**Closed** 2024-09-30 00:08 UTC
Labels: duplicate
