### ISSUE TITLE
Current Implementation of Defense Drone Fix is non-functional.

### ISSUE THREAD

**Issue by slowriderxcorps** [FTL-Hyperspace/FTL-Hyperspace#374] opened 2024-10-17 15:27 UTC
Putting this up there while I still remember that it's been an issue for as long as I have known of HS' existence. The tech has no tangible effet on anything and is seemingly programmed correctly(?), but it is failing to be called correctly so that it can actually do things.

**Comment by ChronoVortex** [comment] 2024-10-17 20:38
Duplicate of #356

**Closed by ChronoVortex** 2024-10-17 20:38 UTC
Labels: duplicate
